version: "3"
services:
  app:
       container_name: Evangelion
       restart: always
       build: .
       ports:
          -8000:8000
       links:
          -mongo
  mongo: 
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"         